# Generated by Django 4.2.3 on 2023-07-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('familya', models.CharField(max_length=30)),
                ('yosh', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='')),
                ('number', models.CharField(choices=[('UZB', '+998'), ('RU', '+721'), ('USA', '+154')], max_length=13)),
            ],
        ),
    ]
